apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-argocd-admin
spec:
  refreshInterval: "15m0s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: argocd-admin-credentials
  data:
  - secretKey: admin.password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: admin-password
      key: argocd
      metadataPolicy: None