apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecrets
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: argocd-admin-credentials
  data:
  - secretKey: admin.password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: admin-password
      key: argocd
      metadataPolicy: None
  - secretKey: github.sshkey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: github-sshkey
      key: argocd
      metadataPolicy: None