apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecret-argocd-repository
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "15m0s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: argocd-private-repo-secret
  data:
  - secretKey: url
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: github-url
      key: argocd
      metadataPolicy: None
  - secretKey: sshPrivateKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: github-sshkey
      key: argocd
      metadataPolicy: None
  - secretKey: name
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: github-name
      key: argocd
      metadataPolicy: None