apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ingressroute-argocd
  namespace: argocd
spec:
  entryPoints:
    - local-https
    - local-http
  routes:
  - kind: Rule
    match: Host(`argocd.local`)
    services:
    - kind: Service
      name: argocd-server
      port: 80