apiVersion: v1
kind: Secret
metadata:
  name: my-private-ssh-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:vaisanenj/K3s-applications.git
  sshPrivateKey:
    valueFrom:
    secretKeyRef:
      name: argocd-admin-credentials
      key: github.sshkey
