apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecrets-alertmanager
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: alertmanager-custom-config
  data:
  - secretKey: alertmanager.yaml
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: alertmanager-config
      key: kube-prometheus-stack
      metadataPolicy: None