apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: externalsecrets-alertmanager
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target: 
    name: alertmanager-secrets
  data:
  - secretKey: discord-webhook-k3s-nodes
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      property: discord-webhook-k3s-nodes
      key: kube-prometheus-stack
      metadataPolicy: None