apiVersion: v2
name: kube-prometheus-stack
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies:
  - name: kube-prometheus-stack
    version: 81.2.2
    repository: https://prometheus-community.github.io/helm-charts