apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-backup-job
spec:
  cron: "30 1 * * *"
  task: "backup"
  groups:
    - default
  retain: 28 # max value is 100
  concurrency: 1
  parameters:
    full-backup-interval: "7" #Full backup every week