apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: longhorn-snapshot-job
spec:
  cron: "15 */2 * * *"
  task: "snapshot"
  groups:
    - default
  retain: 60 # max value is 100
  concurrency: 1